### ISSUE TITLE
An alternative to the timer

### ISSUE THREAD

**Issue by gedankenexperimenter** [keyboardio/Kaleidoscope-DualUse#1]
I don't know if this is possible (I still find most of the Akela and Keyboardio Firmware code impenetrable, possibly because of the lack of comments and documentation), but I want to suggest a different behaviour.  Rather than using a timer to decide if a keypress is a "hold" as opposed to a "tap", I'd prefer it if the decision was made only when any key is _released_.  I'd have it work like this:

After a DualUse modifier key is pressed, if it is the first key released, then register it as its normal keycode.  If some other key is pressed _and released_ before the DualUse modifier is released, then register the modifier keycode instead.

If this is doable, it ought to do a better job of eliminating the potential problem of fast typing triggering unintentional DualUse modifiers.  If the user's timing is slightly off, and they press another key before the DualUse keyswitch is released, but the DualUse key is still released first, everything should be fine, whereas with the current behaviour, they'd get an accidental modifier.  (That's just with overlap, of course – they still get the modifier if they accidentally hold the DualUse key longer than other keys).  I think the tricky bit is dealing with overlap on the other side (normal key pressed first, then DualUse key), but I don't know how tricky that would be.

**Comment by algernon** [comment]
I have entertained a similar idea, and in fact, that is how I originally planned to implement it. There are a number of downsides, though:

Timers
---------

If you want to augment another peripheral (say, a mouse) with the modifier, then there won't be another key pressed to turn the dual-use key into a modifier. For this scenario, you need a timer. This behaviour has been requested for QMK, so there's a need for it outside of my imagination =)

If I get rid of timers, we lose the first behaviour, and that would be unfortunate, because you would not be able to `Alt + Drag` a window, unless you put a plain old `Alt` key on the layout, defeating the purpose of dual-use keys.

Trigger on releasing the other key
----------------------------------------------

If we turn the dual-use key into a modifier when releasing another key, then you can't have that key on repeat. You can't do `Shift/Z + -` (and hold both) to have a line of `________`s, and that's something I wouldn't want to lose, either.

Similarly, if we need the other key to release before triggering the alternate dual-use behaviour, that presents a problem for dual-use layer keys: there are many cases where you want to hold the other key, like navigation keys, volume, mouse keys, and so on. Triggering the alternate on release would severely cripple these cases. Not to mention that it would require a lot more bookeeping...

Summary
-------------

Both the timer, and the trigger-on-press behaviour is there intentionally, for use cases seen in the wild. Unfortunately, they do make fast typing more error prone in the presence of dual-use keys, but that's a trade-off I had to make, and I believe that the current behaviour is more useful than the alternative.

What I could try, is to have another - very short - timer, that would help with the following: if a dual-use key is pressed, and another is pressed in quick succession, before the dual-use key is released, if this new timer has not expired, treat the dual-use key as a normal key. What this means, is that to have the modifier/layer effect, you'd have to hold the dual-use key a bit longer before it activates, but not as long as with the other timer.

Say, we could set it to 20 cycles, which is half of the current timer, and is about 100ms. If you press a `Ctrl/Z` key, release it, and press `A` while the dual-use key is still going up, before the 100ms is up, it would register  as `ZA`. But if you hold `Ctrl/Z` a bit longer, 1/10th of a second, and then press `A`, it could come out as `Ctrl+A`.

Do you think this new timer would help?

**Comment by gedankenexperimenter** [comment]
So, it's been quite a while since I first brought this up, and I don't know what the status is now, but it doesn't hurt to elaborate, since I'm thinking about it again.

First, I don't care about the loss of repeating keys when I'm typing (and when playing games I'd want to have the keyboard in a mode without DualUse altogether, regardless).

Second, having dedicated modifier keys on the keyboard does not defeat my purpose for wanting DualUse keys, as you claimed (in fact, my intention is to have both). Instead, the idea is to make chording the four common modifiers easy and comfortable, with one set on the fingers of each hand.

Third, I don't care about potential problems with DualUse layer keys, because I have no desire to use any.

The one compelling point you made was regarding using the DualUse modifiers with other input devices.

The additional timer sounds like it could cause as many errors as it would fix, as well as being frustrating by forcing a slowdown in using those modifiers. On the other hand, it would be adjustable, and presents a potential practical solution to a potential problem, so I don't see any real problem with having it. I do think 100ms is much too long a default delay, however.

Also, my intended usage is clearly very different than yours, so I may simply have to make my own version of this module to get what I want.

**Comment by algernon** [comment]
I'd be very interested in making - or at least trying to - make DualUse work for your use-case too, as long as existing use-cases are unaffected. If DualUse can be made to function like you want with a few tweakable settings, I'd love to do that.

(I'll have to re-read the original request, mind you, I all but forgotten what it was about, and DualUse changed considerably since then anyway).

**Comment by gedankenexperimenter** [comment]
I've thought it over a bit more, and am convinced that my idea was not as good as the design you implemented. I think your second timer (the modifier/layer doesn't activate immediately on press, but has a short delay in order to address fast typing errors) is a good idea, but the default should probably be zero (or something very short, like 10ms), so that very fast typists can change it, but others can just be unaware of it, and type a modified key immediately.
