### ISSUE TITLE
Shift doesn't work with a tapped dual-use key

### ISSUE THREAD

**Issue by kejadlen** [keyboardio/Kaleidoscope-DualUse#6]
I have a `CMD_T(Tab)` key, but when holding shift and tapping that key, I don't get the same result as holding shift and tapping `Key_Tab`.

**Comment by algernon** [comment]
I see why this would happen: [this line](https://github.com/keyboardio/Kaleidoscope-DualUse/blob/master/src/Kaleidoscope/DualUse.cpp#L106) is the culprit. When releasing a `DualUse` key, we need to first let the host know we pressed it, so the current code does that, and sends a report. But the `Shift` may not be in that report yet, because Kaleidoscope clears the report each cycle.

Solving this is... not trivial. One way to do so would be to return `Key_NoKey` in the event handler, and do the press + release dance in the loop hook, when the report already contains all pressed keys. That may have other side effects, however.

Will try to figure something out in the next day or two.

**Comment by indirect** [comment]
I literally just came here to open this ticket. Thank you for being ahead of me, everyone. :)

**Comment by kejadlen** [comment]
Another difference I noticed, although I'm not sure if it is due to the same root cause: holding cmd and clicking does not have the expected result as well.

@algernon Thanks for all the work on the firmware+plugins - I really appreciate it and if there's a better mechanism you'd prefer for getting these sorts of bugs or anything else I can do to help, just let me know!

**Comment by algernon** [comment]
GitHub issues are the perfect thing for these reports!

**Comment by kejadlen** [comment]
Something interesting I noticed - fn+dual_use(cmd)+brace on the same half does work, but not when either of the latter keys spans across the other half of the keyboard.

For reference, my current layout: https://github.com/kejadlen/Model01-Firmware/blob/alphadox/Model01-Firmware.ino. This is an approximation of my qmk ergodox layout here: https://github.com/kejadlen/qmk_firmware/blob/master/layouts/community/ergodox/alphadox/keymap.c

**Comment by algernon** [comment]
Yeah, this is due to the same reason, scan order, by the looks of it. I have a feeling I know a way to fix these issues across the board, not just in this plugin, but in a few others too. Will dump my ideas somewhere as soon as I have the time & resources to do so.

Thanks for the additional data on the issue!

**Comment by Haegin** [comment]
I've got a custom keyboard layout using this plugin with `L_GUI(Space)` on the left keyboard (the key labelled bksp if that matters) and a key using `LT(FUNCTIONS, Tab)` on the right keyboard (the alt key). Holding the left key (for L_GUI - Cmd on Mac) and tapping the right key (tab) doesn't switch windows. Similarly holding the same key down and tapping the key I have set as `LT(NUMPAD, Enter)` also doesn't work.

The result of holding the cmd key, tapping the tab key and releasing the cmd key (recorded by Karabiner's Event Viewer) is shown below. It appears that the cmd flag is being removed before tab is sent, then the cmd flag is added again after tab is released.

```
eventType:FlagsChanged    code:0x37       name:left_command    flags:Cmd                                misc:
eventType:FlagsChanged    code:0x37       name:left_command    flags:                                   misc:
eventType:KeyDown         code:0x30       name:tab             flags:                                   misc:
eventType:KeyUp           code:0x30       name:tab             flags:                                   misc:
eventType:FlagsChanged    code:0x37       name:left_command    flags:Cmd                                misc:
eventType:FlagsChanged    code:0x37       name:left_command    flags:                                   misc:
```

Is this the same issue? Otherwise I'll report it separately.

**Comment by gedankenexperimenter** [comment]
That sounds like the same issue, yes.

If you'd like to try it, I've written another plugin with essentially the same functionality that doesn't suffer from this scan order issue. It's called [Kaleidoscope-Qukeys](https://github.com/gedankenlab/Kaleidoscope-Qukeys), and it can now be used as a drop-in replacement for DualUse.

**Comment by algernon** [comment]
I'd recommend trying Qukeys, it is now a drop-in replacement, with a fraction (none?) of the bugs that plague DualUse.

**Comment by Haegin** [comment]
I've now switched to Qukeys and it's working great. Thanks for the help and for all the work putting together such a feature complete firmware. I was rather worried that I wasn't going to be able to replicate my QMK setup from my Ergodox but it's been pretty easy to do so.

**Comment by algernon** [comment]
As this works with `Qukeys`, and `DualUse` is now a thin wrapper around that, I'm closing the issue.
