### ISSUE TITLE
Timeout inconsistent behavior with LT and MT

### ISSUE THREAD

**Issue by noctuid** [keyboardio/Kaleidoscope-DualUse#9]
My understanding of the timeout is that the dualuse key shouldn't act as a modifier until the timeout is reached. However, this is only the case for me when using `LT`. With `MT`, the key will immediately act as a modifier when pressed with another key, and the timeout is just how long the key has to be pressed before it stops acting as the normal key when pressed and released by itself.

Please keep this behavior as an option though. The dualuse key immediately acting as a modifier when pressed with other keys and timing out to do nothing when pressed alone is the most generally useful behavior (especially on the keyboardio which has lots of thumb keys; it's not as necessary to give a key like space, which could cause typing errors, a dualuse).

I think it might make sense to have a boolean flag for each MT/LT that would specify whether the timeout corresponds to how long to wait before making the key act as a modifier or only how long to wait before no longer acting as the normal key (only when the key is pressed and released by itself). Edit: To clarify, in both cases the dualuse key would not act as the non-modifier it was held passed the timeout and then released by itself. However, in the second case, the key would always act as a modifier if it was depressed at the same time as another key.

**Comment by algernon** [comment]
With a recent change, `DualUse` is now a wrapper around `Qukeys`, and I'm not sure how that works under the scenarios described here...

Paging @gedankenexperimenter for comment O:)

**Comment by algernon** [comment]
In that case, I'm closing this. Thank you!

**Comment by noctuid** [comment]
@gedankenexperimenter Does Qukeys support allowing the key to immediately act as a modifier when pressed at the same time as another key but still act as a "normal" key when pressed and released by itself (i.e. the timer is for when it stops acting as a normal key and starts *only* acting as a modifier)? That is the main behavior (for the old `MT`) that I wanted and was requesting be kept. I've been meaning to try Qukeys out; I will look at when I get the chance. Thanks.

**Comment by gedankenexperimenter** [comment]
Qukeys doesn't start sending either keycode when a qukey is pressed; it waits until a key is released (or it times out). So both the qukey _and_ the next key pressed do nothing until one of them is _released_. If the qukey is released first, it sends its primary (printable) keycode; if the other key is released first, it sends the alternate (modifier) keycode. Then, the other key's keycode gets added.

This means that it is possible to "roll over" from a qukey to another key without triggering the qukey's alternate keycode, as long as the order of key release is the same as the order of key press. It also means that you can use the alternate keycode without needing to pause at all, as long as you press the qukey first, and release it last.

If you press or release the two keys simultaneously, you might not get what you expect, because of the inherent race condition. On the release side, there is a configurable delay to help people who are in the habit of simultaneously releasing both the modifier and the modified key, and on the other end, there's a race condition for any plain modifier, anyway.

**Comment by gedankenexperimenter** [comment]
The original purpose of the Qukeys timeout was so that alterate-keycode modifiers could be used with external devices, but it does mean that any qukey held long enough starts sending its alternate keycode. I did come up with another use case for it, though — if you define a qukey with a printable alt `Key`, such as `LSHIFT(Key_A)`, or perhaps `LockLayer(FUNCTION)`, you could use a kind of "long-press" to activate it.
